# Generated by Django 2.2.4 on 2020-01-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('origin_state', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start of Leave')),
                ('end_date', models.DateField(help_text='End of Leave')),
                ('leave_type', models.IntegerField(choices=[(0, 'Study'), (1, 'Medical'), (2, 'Emergency'), (3, 'Vacation'), (4, 'Other')], default=0)),
                ('reason_for_leave', models.TextField(max_length=250)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ManageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_decision', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('manage_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.LeaveRequest')),
            ],
        ),
    ]
